[2021-12-08 18:22:39,433] {processor.py:163} INFO - Started process (PID=184) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:22:39,434] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:22:39,434] {logging_mixin.py:109} INFO - [2021-12-08 18:22:39,434] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:22:39,449] {logging_mixin.py:109} INFO - [2021-12-08 18:22:39,435] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:22:39,458] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:22:39,683] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.253 seconds
[2021-12-08 18:23:29,573] {processor.py:163} INFO - Started process (PID=219) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:23:29,596] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:23:29,596] {logging_mixin.py:109} INFO - [2021-12-08 18:23:29,596] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:23:29,598] {logging_mixin.py:109} INFO - [2021-12-08 18:23:29,597] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:23:29,609] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:23:29,764] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.194 seconds
[2021-12-08 18:23:48,830] {processor.py:163} INFO - Started process (PID=233) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:23:48,830] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:23:48,831] {logging_mixin.py:109} INFO - [2021-12-08 18:23:48,831] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:23:48,832] {logging_mixin.py:109} INFO - [2021-12-08 18:23:48,832] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:23:48,841] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:23:48,985] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.157 seconds
[2021-12-08 18:24:08,371] {processor.py:163} INFO - Started process (PID=247) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:24:08,382] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:24:08,382] {logging_mixin.py:109} INFO - [2021-12-08 18:24:08,382] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:24:08,384] {logging_mixin.py:109} INFO - [2021-12-08 18:24:08,383] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:24:08,393] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:24:08,531] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.163 seconds
[2021-12-08 18:24:27,709] {processor.py:163} INFO - Started process (PID=262) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:24:27,710] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:24:27,710] {logging_mixin.py:109} INFO - [2021-12-08 18:24:27,710] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:24:27,712] {logging_mixin.py:109} INFO - [2021-12-08 18:24:27,711] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:24:27,721] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:24:27,898] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.191 seconds
[2021-12-08 18:24:45,732] {processor.py:163} INFO - Started process (PID=275) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:24:45,757] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:24:45,758] {logging_mixin.py:109} INFO - [2021-12-08 18:24:45,758] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:24:45,760] {logging_mixin.py:109} INFO - [2021-12-08 18:24:45,759] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:24:45,772] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:24:45,911] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.181 seconds
[2021-12-08 18:25:05,409] {processor.py:163} INFO - Started process (PID=289) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:25:05,409] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:25:05,410] {logging_mixin.py:109} INFO - [2021-12-08 18:25:05,410] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:25:05,411] {logging_mixin.py:109} INFO - [2021-12-08 18:25:05,411] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:25:05,420] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:25:05,578] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.172 seconds
[2021-12-08 18:25:25,829] {processor.py:163} INFO - Started process (PID=304) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:25:25,847] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:25:25,848] {logging_mixin.py:109} INFO - [2021-12-08 18:25:25,847] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:25:25,849] {logging_mixin.py:109} INFO - [2021-12-08 18:25:25,849] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:25:25,858] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:25:26,001] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.175 seconds
[2021-12-08 18:25:44,366] {processor.py:163} INFO - Started process (PID=318) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:25:44,366] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:25:44,367] {logging_mixin.py:109} INFO - [2021-12-08 18:25:44,367] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:25:44,368] {logging_mixin.py:109} INFO - [2021-12-08 18:25:44,368] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:25:44,378] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:25:44,535] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.172 seconds
[2021-12-08 18:26:03,518] {processor.py:163} INFO - Started process (PID=332) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:26:03,530] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:26:03,531] {logging_mixin.py:109} INFO - [2021-12-08 18:26:03,531] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:26:03,534] {logging_mixin.py:109} INFO - [2021-12-08 18:26:03,533] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:26:03,558] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:26:03,725] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.213 seconds
[2021-12-08 18:26:24,398] {processor.py:163} INFO - Started process (PID=347) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:26:24,399] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:26:24,399] {logging_mixin.py:109} INFO - [2021-12-08 18:26:24,399] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:26:24,402] {logging_mixin.py:109} INFO - [2021-12-08 18:26:24,400] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:26:24,414] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:26:24,559] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.164 seconds
[2021-12-08 18:26:42,792] {processor.py:163} INFO - Started process (PID=362) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:26:42,805] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:26:42,806] {logging_mixin.py:109} INFO - [2021-12-08 18:26:42,806] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:26:42,808] {logging_mixin.py:109} INFO - [2021-12-08 18:26:42,807] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:26:42,817] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:26:43,047] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.258 seconds
[2021-12-08 18:27:01,219] {processor.py:163} INFO - Started process (PID=375) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:27:01,220] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:27:01,221] {logging_mixin.py:109} INFO - [2021-12-08 18:27:01,221] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:27:01,223] {logging_mixin.py:109} INFO - [2021-12-08 18:27:01,222] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:27:01,236] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:27:01,445] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.229 seconds
[2021-12-08 18:27:20,470] {processor.py:163} INFO - Started process (PID=389) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:27:20,480] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:27:20,481] {logging_mixin.py:109} INFO - [2021-12-08 18:27:20,481] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:27:20,483] {logging_mixin.py:109} INFO - [2021-12-08 18:27:20,482] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:27:20,493] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:27:20,736] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.269 seconds
[2021-12-08 18:27:42,356] {processor.py:163} INFO - Started process (PID=404) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:27:42,357] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:27:42,357] {logging_mixin.py:109} INFO - [2021-12-08 18:27:42,357] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:27:42,359] {logging_mixin.py:109} INFO - [2021-12-08 18:27:42,358] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:27:42,370] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:27:42,613] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.260 seconds
[2021-12-08 18:28:03,150] {processor.py:163} INFO - Started process (PID=419) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:03,166] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:28:03,166] {logging_mixin.py:109} INFO - [2021-12-08 18:28:03,166] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:03,168] {logging_mixin.py:109} INFO - [2021-12-08 18:28:03,167] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:28:03,178] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:03,329] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.182 seconds
[2021-12-08 18:28:23,508] {processor.py:163} INFO - Started process (PID=434) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:23,508] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:28:23,508] {logging_mixin.py:109} INFO - [2021-12-08 18:28:23,508] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:23,510] {logging_mixin.py:109} INFO - [2021-12-08 18:28:23,510] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:28:23,520] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:23,683] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.178 seconds
[2021-12-08 18:28:41,515] {processor.py:163} INFO - Started process (PID=448) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:41,531] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:28:41,532] {logging_mixin.py:109} INFO - [2021-12-08 18:28:41,532] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:41,535] {logging_mixin.py:109} INFO - [2021-12-08 18:28:41,534] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:28:41,544] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:41,686] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.175 seconds
[2021-12-08 18:28:59,189] {processor.py:163} INFO - Started process (PID=461) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:59,189] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:28:59,190] {logging_mixin.py:109} INFO - [2021-12-08 18:28:59,190] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:59,191] {logging_mixin.py:109} INFO - [2021-12-08 18:28:59,191] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:28:59,201] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:28:59,373] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.187 seconds
[2021-12-08 18:29:17,381] {processor.py:163} INFO - Started process (PID=474) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:29:17,394] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:29:17,394] {logging_mixin.py:109} INFO - [2021-12-08 18:29:17,394] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:29:17,396] {logging_mixin.py:109} INFO - [2021-12-08 18:29:17,395] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:29:17,406] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:29:17,551] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.173 seconds
[2021-12-08 18:29:37,980] {processor.py:163} INFO - Started process (PID=489) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:29:37,981] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:29:37,982] {logging_mixin.py:109} INFO - [2021-12-08 18:29:37,982] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:29:37,984] {logging_mixin.py:109} INFO - [2021-12-08 18:29:37,984] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:29:37,993] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:29:38,129] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.152 seconds
[2021-12-08 18:29:58,605] {processor.py:163} INFO - Started process (PID=504) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:29:58,634] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:29:58,635] {logging_mixin.py:109} INFO - [2021-12-08 18:29:58,634] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:29:58,637] {logging_mixin.py:109} INFO - [2021-12-08 18:29:58,636] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:29:58,649] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:29:58,811] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.208 seconds
[2021-12-08 18:30:16,124] {processor.py:163} INFO - Started process (PID=518) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:30:16,124] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:30:16,125] {logging_mixin.py:109} INFO - [2021-12-08 18:30:16,125] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:30:16,126] {logging_mixin.py:109} INFO - [2021-12-08 18:30:16,126] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:30:16,136] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:30:16,333] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.212 seconds
[2021-12-08 18:30:34,295] {processor.py:163} INFO - Started process (PID=531) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:30:34,296] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:30:34,296] {logging_mixin.py:109} INFO - [2021-12-08 18:30:34,296] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:30:34,298] {logging_mixin.py:109} INFO - [2021-12-08 18:30:34,297] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:30:34,307] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:30:34,498] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.206 seconds
[2021-12-08 18:30:53,550] {processor.py:163} INFO - Started process (PID=545) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:30:53,550] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:30:53,551] {logging_mixin.py:109} INFO - [2021-12-08 18:30:53,551] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:30:53,552] {logging_mixin.py:109} INFO - [2021-12-08 18:30:53,552] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:30:53,561] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:30:53,701] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.154 seconds
[2021-12-08 18:31:12,624] {processor.py:163} INFO - Started process (PID=560) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:31:12,636] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:31:12,637] {logging_mixin.py:109} INFO - [2021-12-08 18:31:12,637] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:31:12,640] {logging_mixin.py:109} INFO - [2021-12-08 18:31:12,639] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:31:12,649] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:31:12,790] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.171 seconds
[2021-12-08 18:31:30,077] {processor.py:163} INFO - Started process (PID=573) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:31:30,077] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:31:30,078] {logging_mixin.py:109} INFO - [2021-12-08 18:31:30,077] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:31:30,079] {logging_mixin.py:109} INFO - [2021-12-08 18:31:30,079] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:31:30,089] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:31:30,244] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.170 seconds
[2021-12-08 18:31:48,589] {processor.py:163} INFO - Started process (PID=586) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:31:48,590] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:31:48,593] {logging_mixin.py:109} INFO - [2021-12-08 18:31:48,592] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:31:48,600] {logging_mixin.py:109} INFO - [2021-12-08 18:31:48,597] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:31:48,619] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:31:48,755] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.171 seconds
[2021-12-08 18:32:08,643] {processor.py:163} INFO - Started process (PID=601) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:32:08,643] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:32:08,643] {logging_mixin.py:109} INFO - [2021-12-08 18:32:08,643] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:32:08,645] {logging_mixin.py:109} INFO - [2021-12-08 18:32:08,645] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:32:08,654] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:32:08,824] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.184 seconds
[2021-12-08 18:32:26,993] {processor.py:163} INFO - Started process (PID=615) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:32:26,994] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:32:26,995] {logging_mixin.py:109} INFO - [2021-12-08 18:32:26,995] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:32:26,997] {logging_mixin.py:109} INFO - [2021-12-08 18:32:26,996] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:32:27,006] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:32:27,157] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.166 seconds
[2021-12-08 18:32:46,609] {processor.py:163} INFO - Started process (PID=629) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:32:46,609] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:32:46,610] {logging_mixin.py:109} INFO - [2021-12-08 18:32:46,609] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:32:46,611] {logging_mixin.py:109} INFO - [2021-12-08 18:32:46,611] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:32:46,621] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:32:46,780] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.174 seconds
[2021-12-08 18:33:07,028] {processor.py:163} INFO - Started process (PID=644) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:07,043] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:33:07,044] {logging_mixin.py:109} INFO - [2021-12-08 18:33:07,043] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:07,045] {logging_mixin.py:109} INFO - [2021-12-08 18:33:07,045] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:33:07,054] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:07,203] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.177 seconds
[2021-12-08 18:33:24,267] {processor.py:163} INFO - Started process (PID=658) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:24,267] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:33:24,267] {logging_mixin.py:109} INFO - [2021-12-08 18:33:24,267] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:24,269] {logging_mixin.py:109} INFO - [2021-12-08 18:33:24,268] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:33:24,278] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:24,435] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.171 seconds
[2021-12-08 18:33:40,368] {processor.py:163} INFO - Started process (PID=671) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:40,369] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:33:40,369] {logging_mixin.py:109} INFO - [2021-12-08 18:33:40,369] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:40,371] {logging_mixin.py:109} INFO - [2021-12-08 18:33:40,370] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:33:40,379] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:40,583] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.219 seconds
[2021-12-08 18:33:56,903] {processor.py:163} INFO - Started process (PID=683) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:56,916] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:33:56,917] {logging_mixin.py:109} INFO - [2021-12-08 18:33:56,917] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:56,918] {logging_mixin.py:109} INFO - [2021-12-08 18:33:56,918] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:33:56,928] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:33:57,116] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.216 seconds
[2021-12-08 18:34:14,655] {processor.py:163} INFO - Started process (PID=696) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:34:14,655] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:34:14,656] {logging_mixin.py:109} INFO - [2021-12-08 18:34:14,656] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:34:14,657] {logging_mixin.py:109} INFO - [2021-12-08 18:34:14,657] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:34:14,666] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:34:14,894] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.242 seconds
[2021-12-08 18:34:34,087] {processor.py:163} INFO - Started process (PID=710) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:34:34,121] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:34:34,121] {logging_mixin.py:109} INFO - [2021-12-08 18:34:34,121] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:34:34,124] {logging_mixin.py:109} INFO - [2021-12-08 18:34:34,123] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:34:34,138] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:34:34,295] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.211 seconds
[2021-12-08 18:34:54,706] {processor.py:163} INFO - Started process (PID=725) to work on /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:34:54,707] {processor.py:625} INFO - Processing file /home/karan/airflow/dags/my_dag.py for tasks to queue
[2021-12-08 18:34:54,707] {logging_mixin.py:109} INFO - [2021-12-08 18:34:54,707] {dagbag.py:500} INFO - Filling up the DagBag from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:34:54,709] {logging_mixin.py:109} INFO - [2021-12-08 18:34:54,708] {dagbag.py:334} ERROR - Failed to import: /home/karan/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/karan/airflow/dags/my_dag.py", line 47
    inaccurate = BashOperator(
    ^
SyntaxError: invalid syntax
[2021-12-08 18:34:54,719] {processor.py:639} WARNING - No viable dags retrieved from /home/karan/airflow/dags/my_dag.py
[2021-12-08 18:34:54,931] {processor.py:171} INFO - Processing /home/karan/airflow/dags/my_dag.py took 0.227 seconds
